spring.application.name=portable-secure-exchange-client
server.address=127.0.0.1
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/secure-exchange;AUTO_SERVER=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.exchange.root=./exchange
app.browser.auto-open=false

vaadin.allowed-packages=com.vaadin,org.vaadin,io.github.nesmachnydn
